/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ChildType,
} from './../dist/types/stencil.core';

export namespace Components {
  interface VirtualScroll {
    'autoDetectSize'?: boolean;
    'itemCount': number;
    'itemHeight'?: number;
    'itemWidth'?: number;
    'renderItem': (i: number) => ChildType | Promise<ChildType>
    | ChildType[] | Promise<ChildType[]> | Promise<ChildType>[];
    'sameSize'?: boolean;
    'tick'?: any;
  }
}

declare global {


  interface HTMLVirtualScrollElement extends Components.VirtualScroll, HTMLStencilElement {}
  var HTMLVirtualScrollElement: {
    prototype: HTMLVirtualScrollElement;
    new (): HTMLVirtualScrollElement;
  };
  interface HTMLElementTagNameMap {
    'virtual-scroll': HTMLVirtualScrollElement;
  }
}

declare namespace LocalJSX {
  interface VirtualScroll {
    'autoDetectSize'?: boolean;
    'itemCount': number;
    'itemHeight'?: number;
    'itemWidth'?: number;
    'renderItem': (i: number) => ChildType | Promise<ChildType>
    | ChildType[] | Promise<ChildType[]> | Promise<ChildType>[];
    'sameSize'?: boolean;
    'tick'?: any;
  }

  interface IntrinsicElements {
    'virtual-scroll': VirtualScroll;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'virtual-scroll': LocalJSX.VirtualScroll & JSXBase.HTMLAttributes<HTMLVirtualScrollElement>;
    }
  }
}


